erp1/urls.py
from django.contrib import admin
from django.urls import path, include
from haystack.views import SearchView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('search/', include('haystack.urls')),
    path('', include('inventory_manage.urls', namespace='inventory_manage')),
    path('work_flow/', include('work_flow.urls', namespace='work_flow')),

]

inventory_manage/urls.py
from django.urls import path
from . import views
app_name='inventory_manage'
urlpatterns = [
    path('', views.index, name='index'),
    path('types', views.inventory, name='type'),
    path('element/<int:type_id>/', views.element, name='element'),
    path('new_type', views.new_type, name='new_type'),
    path('new_element/<int:type_id>', views.new_element, name='new_element'),
    path('edit_element/<int:element_id>', views.edit_element, name='edit_element'),
    #path('search/', views.My_search, name='My_search'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import login
from . import views
app_name='users'
urlpatterns = [
    path('login/', login, {'template_name': 'users/login.html'}, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
]

work_flow/urls.py
from django.urls import path
from . import views
app_name = 'work_flow'
urlpatterns = [
    path('', views.overview, name='overview'),
    path('<int:E_O_id>', views.detials, name='detials'),
    path('new_element/', views.new_element, name='new_element'),
    path('new_step/<int:element_id>/', views.new_step, name='new_step'),

    path('edit_working/<int:element_id>/', views.edit_working, name='edit_working'),
    path('edit_step/<int:step_id>', views.edit_step, name='edit_step'),
]

inventory_manage/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Inventory(models.Model):
    inventory_type = models.CharField(max_length=50)
    #number = models.IntegerField(max_length=10)
    #material = models.CharField(max_length=20)
    date_add = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural = '库存类别'
    def __str__(self):
        return self.inventory_type

class Element(models.Model):
    type = models.ForeignKey(Inventory, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    number = models.IntegerField()
    material = models.CharField(max_length=20)
    bianhao = models.CharField(max_length=30)
    date_add = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = '详细库存'

    def __str__(self):
        return self.name

inventory_manage/forms.py
from django import forms
from .models import Inventory, Element

class TypeForm(forms.ModelForm):
    class Meta:
        model = Inventory
        fields = ['inventory_type']
        labels = {'inventory_type': '添加合适的类别，如抽油泵零件、数控刀具等'}

class ElementForm(forms.ModelForm):
    class Meta:
        model = Element
        fields = ['name', 'number', 'material']
        labels = {'name': '零件名称', 'number': '零件数量', 'material': '零件材质'}

inventory_manage/views.py
from django.shortcuts import render
from .models import Inventory, Element
from .forms import TypeForm, ElementForm
from django.http import  HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from haystack.forms import SearchForm
# Create your views here.
def index(request):
    return render(request, 'inventory_manage/index.html')

@login_required
def inventory(request):
    types = Inventory.objects.order_by('date_add')
    context = {'types': types}
    return render(request, 'inventory_manage/type.html', context)

@login_required
def element(request, type_id):
    type = Inventory.objects.get(id=type_id)
    elements = type.element_set.order_by('-date_add')
    context = {'type': type, 'elements': elements}
    return render(request, 'inventory_manage/element.html', context)

@login_required
def new_type(request):
    if request.method != 'POST':
        form = TypeForm()
    else:
        form = TypeForm(request.POST)
        if form.is_valid():
            new_type = form.save(commit=False)
            new_type.owner = request.user
            new_type.save()
        return HttpResponseRedirect(reverse('inventory_manage:type'))

    context = {'form': form}
    return render(request, 'inventory_manage/new_type.html', context)

@login_required
def new_element(request, type_id):
    type = Inventory.objects.get(id=type_id)

    if request.method != 'POST':
        form = ElementForm
    else:
        form = ElementForm(data=request.POST)
        if form.is_valid():
            new_element = form.save(commit=False)
            new_element.type = type
            new_element.save()
        return HttpResponseRedirect(reverse('inventory_manage:element', args=[type_id]))
    context = {'type': type, 'form': form}
    return render(request, 'inventory_manage/new_element.html', context)

@login_required
def edit_element(request, element_id):
    element = Element.objects.get(id=element_id)
    type = element.type

    if request.method != 'POST':
        form = ElementForm(instance=element)
    else:
        form = ElementForm(instance=element, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('inventory_manage:element', args=[type.id]))

    context = {'element': element, 'type': type, 'form': form}
    return render(request,'inventory_manage/edit_element.html', context)

inventory_manage/templates/inventory_manage/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <title>生产流程管理系统</title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>

    <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-expand-sm bg-primary navbar-dark">
        <a class="navbar-brand" href="{% url 'inventory_manage:index' %}">工具加工车间生产流程管理系统</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'work_flow:overview' %}">正在生产<span class="sr-only">(current)</span></a>

                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'inventory_manage:type' %}">库存管理<span class="sr-only">(current)</span></a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">

             <form class="form-inline" method='get' action="{% url 'haystack_search' %}" target="_blank">
                <input class="form-control mr-sm-2" type="text" name="q"  placeholder="库存查询">
                <input class="btn btn-outline-light my-2 my-sm-0" type="submit" value="查询">
            </form>

                {% if user.is_authenticated %}
                    <li class="nav-item active">
                       <a class="nav-link">欢迎 {{ user.username }}，</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'users:logout' %}">注销</a>
                    </li>
                {% else %}
                    <li class="nav-item active"><a class="nav-link" href="{% url 'users:register' %}">注册</a></li>
                    <li class="nav-item active"><a class="nav-link" href="{% url 'users:login' %}">登陆</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div> <!-- /container -->
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    </body>
</html>

inventory_manage/templates/inventory_manage/edit_element.html
{% extends "inventory_manage/base.html" %}
{% load bootstrap4 %}
{% block hesder %}
    <h2>编辑你的条目</h2>
{% endblock hesder %}

{% block content %}

 <br/>
    <div class="container">

  <div class="card">
    <div class="card-header">
        <div style="width:200px;height:20px;float:left;">
               <h2>编辑零件</h2> </div>
        <div style="width:100px;height:20px;float:right;">
                <h2><a href="{% url 'inventory_manage:element' type.id %}">{{ type }}</a></h2>
        </div><br/><br/>
    </div>

    <div class="card-body">
       <form action="{% url 'inventory_manage:edit_element' element.id %}" method='post' class="form">
{% csrf_token %}
{% bootstrap_form form %}
{% buttons %}
    <button name="submit" class="btn btn-primary">提交更改</button>
{% endbuttons %}
</form>
    </div>

  </div>
</div>

{% endblock content %}

inventory_manage/templates/inventory_manage/element.html
{% extends 'inventory_manage/base.html' %}
{% block header %}
    <br/>
<div class="container">
    <div class="card">
        <div class="card-body ">
            <div class="row">
                <h2>{{ type }}</h2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <a class="btn btn-lg btn-primary" href="{% url 'inventory_manage:new_element' type.id %}" role="button">添加新零件</a>
            </div>
        </div>
    </div>
</div>

{% endblock header %}
{% block content %}
<br/>

    <div class="container">
    <div class="row tool-list">
        {% for element in elements %}
        <div class="col-md-6 col-lg-4 col-xl-3 px-lg-2 mb-3 ">
            <div class="card ">
                <div class="card-header">

                    <div style="width:150px;height:20px;float:left;">
                            <h4>{{ element.name|linebreaks }}</h4>
                        </div>
                    <div style="width:50px;height:20px;float:right;">
                    <a class="btn btn-info" role="button" href="{% url 'inventory_manage:edit_element' element.id %}" >编辑</a>
                    </div><br/><br/>

                </div>
                <div class="card-body m-auto">
                    <h3>
                        <div style="width:100px;height:20px;float:left;">
                            数量：</div>
                        <div style="width:100px;height:20px;float:left;">
                            {{ element.number|linebreaks }}</div>
                        <br/>
                        <div style="width:100px;height:20px;float:left;">
                            材质：</div>
                        <div style="width:100px;height:20px;float:left;">
                            {{ element.material|linebreaks }}</div>
                        <br/>
                        <div style="width:100px;height:20px;float:left;">
                            编号：</div>
                        <div style="width:100px;height:20px;float:left;">
                            {{ element.bianhao|linebreaks }}</div>
                        <br/>
                    </h3>
                </div>
                <div class="card-footer">
                    日期：{{ element.date_add|date:'Y-m-d H:i:s' }}
                </div>
            </div>
        </div>
        {% empty %}
            <div class="alert alert-danger">
                <strong>请添加库存零件！</strong>
            </div>
        {% endfor %}
    </div>
</div>


{% endblock content %}

inventory_manage/templates/inventory_manage/index.html
{% extends "inventory_manage/base.html" %}
{% block header %}
    <div class='jumbotron'>
        <h3>工具加工车间生产流程管理系统简介</h3>
        <h4>此系统是为了满足ISO9001及API Q1质量体系的要求而开发的。
            达到了车间对生产流程和库存零件进行实时管理的需求。通过此系统，车间调度可以随时创建新的生产计划，
            生产流程的每一步都能实时反馈，当检验员检验合格后点击合格按钮即可进行下一流程。
            <br>库存管理可以快捷灵活的添加并查看所有库存零件及刀具、工具、量具等。</h4>
        <h5>
        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">点击这里创建用户</a>

        </h5>
    </div>
{% endblock header %}
{% block content %}


{% endblock content %}

inventory_manage/templates/inventory_manage/new_element.html
{% extends "inventory_manage/base.html" %}
{% load bootstrap4 %}
{% block header %}


{% endblock header %}

{% block content %}

<br/>
    <div class="container">

  <div class="card">
    <div class="card-header">
        <div style="width:200px;height:20px;float:left;">
               <h2>添加新零件</h2> </div>
        <div style="width:200px;height:20px;float:right;">
                <h3><a href="{% url 'inventory_manage:element' type.id %}">{{ type }}</a></h3>
        </div><br/><br/>
    </div>

    <div class="card-body"><form action="{% url 'inventory_manage:new_element' type.id %}" method='post' class="form">
{% csrf_token %}
 {% bootstrap_form form %}

{% buttons %}
<button name='submit' class="btn-primary">添加</button>
{% endbuttons %}
</form></div>

  </div>
</div>



{% endblock content %}

inventory_manage/templates/inventory_manage/new_type.html
{% extends "inventory_manage/base.html" %}
{% load bootstrap4 %}



{% block content %}
    <br/>
    <div class="container">

  <div class="card">
    <div class="card-header"><h2>添加新类别</h2></div>
    <div class="card-body"><form action="{% url 'inventory_manage:new_type' %}" method='post'
        class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button name="submit" class="btn btn-primary">提交</button>
    {% endbuttons %}
    </form></div>
    <div class="card-footer">

    </div>
  </div>
</div>

{% endblock content %}

inventory_manage/templates/inventory_manage/type.html
{% extends "inventory_manage/base.html" %}
{% load bootstrap4 %}
{% block header %}
<br/>

<div class="container">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <h2>库存类别</h2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <a class="btn btn-lg btn-primary" href="{% url 'inventory_manage:new_type' %}" role="button">添加库存类别</a>
            </div>
        </div>
    </div>
</div>
{% endblock header %}

{% block content %}
<br/>
<main>
<div class="container">
    <div class="row tool-list">
        {% for type in types %}
        <div class="col-md-6 col-lg-4 col-xl-3 px-lg-2 mb-3 ">
            <div class="card ">
                <div class="card-body m-auto">
                    <h3><a href="{% url 'inventory_manage:element' type.id %}">{{ type }}</a></h3>
                </div>
            </div>
        </div>
        {% empty %}
            <div class="alert alert-danger">
                <strong>请添加库存类别！</strong>
            </div>
        {% endfor %}
    </div>
</div>

<div class="text-center" id="to-top">
    <i class="fa fa-chevron-up" id="btn-top" title="回到顶部"></i>
</div>
</main>
{% endblock content %}