erp1/urls.py
from django.contrib import admin
from django.urls import path, include
from haystack.views import SearchView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('search/', include('haystack.urls')),
    path('', include('inventory_manage.urls', namespace='inventory_manage')),
    path('work_flow/', include('work_flow.urls', namespace='work_flow')),

]

work_flow/urls.py
from django.urls import path
from . import views
app_name = 'work_flow'
urlpatterns = [
    path('', views.overview, name='overview'),
    path('<int:E_O_id>', views.detials, name='detials'),
    path('new_element/', views.new_element, name='new_element'),
    path('new_step/<int:element_id>/', views.new_step, name='new_step'),

    path('edit_working/<int:element_id>/', views.edit_working, name='edit_working'),
    path('edit_step/<int:step_id>', views.edit_step, name='edit_step'),
]

work_flow/models.py
from django.db import models

# Create your models here.
class Ele_Overview(models.Model):
    name = models.CharField(max_length=50)
    number = models.IntegerField()
    material = models.CharField(max_length=20)
    code = models.CharField(max_length=20)
    flag = models.NullBooleanField()
    date_add = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = '零件概览'

    def __str__(self):
        return self.name

class Detial(models.Model):
    type = models.ForeignKey(Ele_Overview, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    flag = models.NullBooleanField()
    date_add = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = '详细工序'

    def __str__(self):
        return self.name

work_flow/forms.py
from django import forms
from .models import Ele_Overview, Detial

class OverviewForm(forms.ModelForm):
    class Meta:
        model = Ele_Overview
        fields = ['name', 'number', 'material', 'flag']
        labels = {'name': '名称', 'number': '数量', 'material': '材质', 'flag': '是否完成'}



class WorkStepForm(forms.ModelForm):
    class Meta:
        model = Detial
        fields = ['name', 'price', 'flag']
        labels = {'name': '工序名称', 'price': '计件价格', 'flag': '是否完成'}

work_flow/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Ele_Overview, Detial
from .forms import OverviewForm, WorkStepForm
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required
def overview(request):
    elements = Ele_Overview.objects.order_by('-date_add')
    context = {'elements': elements}
    return render(request, 'work_flow/overview.html', context)

@login_required
def detials(request, E_O_id):
    E_O = Ele_Overview.objects.get(id=E_O_id)
    work_steps = E_O.detial_set.order_by('-date_add')
    context = {'E_O': E_O, 'work_steps': work_steps}
    return render(request, 'work_flow/detials.html', context)

@login_required
def new_element(request):
    if request.method != 'POST':
        form = OverviewForm()
    else:
        form = OverviewForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('work_flow:overview'))
    context = {'form': form}
    return render(request, 'work_flow/new_element.html', context)


@login_required
def new_step(request, element_id):
    element = Ele_Overview.objects.get(id=element_id)
    if request.method != 'POST':
        form = WorkStepForm()
    else:
        form = WorkStepForm(data=request.POST)
        if form.is_valid():
            new_step = form.save(commit=False)
            new_step.type = element
            new_step.save()
            return HttpResponseRedirect(reverse('work_flow:detials', args=[element_id]))
    context = {'element': element, 'form': form}
    return render(request, 'work_flow/new_step.html', context)

@login_required
def edit_working(request, element_id):
    element = Ele_Overview.objects.get(id=element_id)
    if request.method != 'POST':
        form = OverviewForm(instance=element)
    else:
        form = OverviewForm(instance=element, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('work_flow:overview'))

    context = {'element': element, 'form': form}
    return render(request, 'work_flow/edit_working.html', context)

@login_required
def edit_step(request, step_id):
    step = Detial.objects.get(id=step_id)
    id = step.type.id
    if request.method != 'POST':
        form = WorkStepForm(instance=step)
    else:
        form = WorkStepForm(instance=step, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('work_flow:detials', args=[id]))

    context = {'step': step, 'form': form}
    return render(request, 'work_flow/edit_step.html', context)

work_flow/templates/work_flow/detials.html
{% extends 'inventory_manage/base.html' %}
{% block header %}

    <br/>
<div class="container">
    <div class="card">
        <div class="card-body ">
            <div class="row">
                <h2>{{ E_O }}</h2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <a class="btn btn-lg btn-primary" href="{% url 'work_flow:new_step' E_O.id %}" role="button">添加工步</a>
            </div>
            <br/><br/>
        </div>
    </div>
</div>

{% endblock header %}

{% block content %}

    <br/>

    <div class="container">
    <div class="row tool-list">
        {% for wksp in work_steps %}
        <div class="col-md-6 col-lg-4 col-xl-4 px-lg-2 mb-3 ">
            <div class="card ">
                <div class="card-header">

                    <div style="width:200px;height:20px;float:left;">
                            <h4>{{ wksp.name|linebreaks }}</h4></div>
                    <div style="width:50px;height:20px;float:right;">
                    <a class="btn btn-info" role="button" href="{% url 'work_flow:edit_step' wksp.id %}" >编辑</a>
                    </div>
                    <br/><br/>
                </div>
                <div class="card-body m-auto">
                    <h3>
                        <div style="width:150px;height:20px;float:left;">
                            计件价格：</div>
                        <div style="width:100px;height:20px;float:right;">
                            {{ wksp.price|linebreaks }}</div>
                        <br/>
                        <div style="width:150px;height:20px;float:left;">
                            是否完成：</div>
                        <div style="width:100px;height:20px;float:right;">
                            {{ wksp.flag|linebreaks }}</div>
                        <br/>

                    </h3>
                </div>
                <div class="card-footer">
                    日期：{{ wksp.date_add|date:'Y-m-d H:i:s' }}
                </div>
            </div>
        </div>
        {% empty %}
            <div class="alert alert-danger">
                <strong>请添加工步！</strong>
            </div>
        {% endfor %}
    </div>
</div>


{% endblock content %}

work_flow/templates/work_flow/edit_step.html
{% extends "inventory_manage/base.html" %}
{% load bootstrap4 %}
{% block header %}

{% endblock header %}

{% block content %}

    <br/>
    <div class="container">

  <div class="card">
    <div class="card-header">
        <div style="width:200px;height:20px;float:left;">
               <h2>编辑工步</h2> </div>
        <div style="width:100px;height:20px;float:right;">

        </div><br/><br/>
    </div>

    <div class="card-body">
       <form action="{% url 'work_flow:edit_step' step.id %}" method='post' class="form">
{% csrf_token %}
{% bootstrap_form form %}
{% buttons %}
    <button name="submit" class="btn btn-primary">提交更改</button>
{% endbuttons %}
</form>
    </div>

  </div>
</div>


{% endblock content %}

work_flow/templates/work_flow/edit_working.html
{% extends "inventory_manage/base.html" %}
{% load bootstrap4 %}
{% block header %}

{% endblock header %}

{% block content %}

<br/>
    <div class="container">

  <div class="card">
    <div class="card-header">
        <div style="width:200px;height:20px;float:left;">
               <h2>编辑生产任务</h2> </div>
        <div style="width:500px;height:20px;float:left;">
                <h2><a href="{% url 'work_flow:overview'  %}">{{ element }}</a></h2>
        </div><br/><br/>
    </div>

    <div class="card-body">
       <form action="{% url 'work_flow:edit_working' element.id %}" method='post' class="form">
{% csrf_token %}
{% bootstrap_form form %}
{% buttons %}
    <button name="submit" class="btn btn-primary">提交更改</button>
{% endbuttons %}
</form>
    </div>

  </div>
</div>



{% endblock content %}

work_flow/templates/work_flow/new_element.html
{% extends "inventory_manage/base.html" %}
{% load bootstrap4 %}
{% block header %}

{% endblock header %}
{% block content %}

<br/>
    <div class="container">

  <div class="card">
    <div class="card-header">

               <h2>添加新生产计划</h2>

    </div>

    <div class="card-body"><form action="{% url 'work_flow:new_element' %}" method='post'
        class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button name="submit" class="btn btn-primary">提交</button>
    {% endbuttons %}
    </form></div>

  </div>
</div>

{% endblock content %}

work_flow/templates/work_flow/new_step.html
{% extends "inventory_manage/base.html" %}
{% load bootstrap4 %}
{% block header %}
    <h2>添加工步</h2>
{% endblock header %}

{% block content %}
 <h3><a href="{% url 'work_flow:detials' element.id %}">返回</a></h3>

 <form action="{% url 'work_flow:new_step' element.id %}" method='post' class="form">
{% csrf_token %}
 {% bootstrap_form form %}

{% buttons %}
<button name='submit' class="btn-primary">添加</button>
{% endbuttons %}
</form>
{% endblock content %}

work_flow/templates/work_flow/overview.html
{% extends "inventory_manage/base.html" %}

{% block header %}

    <br/>

<div class="container">
    <div class="card">
        <div class="card-body">

                <div class="row">
                <h2>正在生产概览</h2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <a class="btn btn-lg btn-primary" href="{% url 'work_flow:new_element' %}" role="button">添加生产任务</a>
                </div>

        </div>
    </div>
</div>

{% endblock header %}

{% block content %}

    <br/>

    <div class="container">
    <div class="row tool-list">
        {% for element in elements %}
        <div class="col-md-6 col-lg-4 col-xl-4 px-lg-2 mb-3 ">
            <div class="card ">
                <div class="card-header">
                    <div style="width:220px;height:20px;float:left;">
                            <h4>{{ element.name|linebreaks }}</h4></div>
                    <div style="width:50px;height:20px;float:right;">
                    <a class="btn btn-info" role="button" href="{% url 'work_flow:edit_working' element.id %}" >编辑</a>
                    </div>
                    <br/><br/>
                </div>
                <div class="card-body ">
                    <h3>
                        <div style="width:100px;height:20px;float:left;">
                            数量：</div>
                        <div style="width:100px;height:20px;float:left;">
                            {{ element.number|linebreaks }}</div>
                        <br/>
                        <div style="width:100px;height:20px;float:left;">
                            材质：</div>
                        <div style="width:100px;height:20px;float:left;">
                            {{ element.material|linebreaks }}</div>
                        <br/>
                        <div style="width:150px;height:20px;float:left;">
                            正在进行：</div>
                        <div style="width:100px;height:20px;float:left;">
                            {{ name|linebreaks }}</div>
                        <br/>
                        <script>
                            if ({{ element.flag}}=true){
                                document.getElementById("bool").innerHTML = "是"
                            }else {
                                document.getElementById("bool").innerHTML = "否"
                            }
                        </script>
                        <div style="width:150px;height:20px;float:left;">
                            是否完成：</div>
                        <div style="width:100px;height:20px;float:left;">
                            {{ element.flag|linebreaks }}
                        </div>
                        <br/>
                    </h3>
                </div>
                <div class="card-footer"><br/>
                    <div style="width:250px;height:20px;float:left;">
                            <h5>日期：{{ element.date_add|date:'Y-m-d H:i:s' }}</h5></div>
                        <div style="width:50px;height:20px;float:right;">
                    <a class="btn btn-info" role="button" href="{% url 'work_flow:detials' element.id %}" >详情</a>
                   </div><br/><br/>
                </div>
            </div>
        </div>
        {% empty %}
            <div class="alert alert-danger">
                <strong>请添加生产计划</strong>
            </div>
        {% endfor %}
    </div>
</div>


{% endblock content %}